//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 10:04:26 AM BRT 
//


package br.org.gs1br.hc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.org.gs1br.hc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.org.gs1br.hc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryRequest }
     * 
     */
    public QueryRequest createQueryRequest() {
        return new QueryRequest();
    }

    /**
     * Create an instance of {@link Infolist }
     * 
     */
    public Infolist createInfolist() {
        return new Infolist();
    }

    /**
     * Create an instance of {@link PreferenceData }
     * 
     */
    public PreferenceData createPreferenceData() {
        return new PreferenceData();
    }

    /**
     * Create an instance of {@link Partner }
     * 
     */
    public Partner createPartner() {
        return new Partner();
    }

    /**
     * Create an instance of {@link QueryRequest.QueryRequestItem }
     * 
     */
    public QueryRequest.QueryRequestItem createQueryRequestQueryRequestItem() {
        return new QueryRequest.QueryRequestItem();
    }

    /**
     * Create an instance of {@link InboundResponse }
     * 
     */
    public InboundResponse createInboundResponse() {
        return new InboundResponse();
    }

    /**
     * Create an instance of {@link ErrorList }
     * 
     */
    public ErrorList createErrorList() {
        return new ErrorList();
    }

    /**
     * Create an instance of {@link QueryResponse }
     * 
     */
    public QueryResponse createQueryResponse() {
        return new QueryResponse();
    }

    /**
     * Create an instance of {@link ResponseList }
     * 
     */
    public ResponseList createResponseList() {
        return new ResponseList();
    }

    /**
     * Create an instance of {@link InboundMessage }
     * 
     */
    public InboundMessage createInboundMessage() {
        return new InboundMessage();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link AttorneyAuthorization }
     * 
     */
    public AttorneyAuthorization createAttorneyAuthorization() {
        return new AttorneyAuthorization();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link QueryResponseItem }
     * 
     */
    public QueryResponseItem createQueryResponseItem() {
        return new QueryResponseItem();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Infolist.Info }
     * 
     */
    public Infolist.Info createInfolistInfo() {
        return new Infolist.Info();
    }

}
