//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.04 at 03:23:26 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://hc.gs1br.org.br/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.org.gs1br.hc;
