<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.med.healthcare.gs1br.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="InboundService" targetNamespace="http://ws.med.healthcare.gs1br.org/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.med.healthcare.gs1br.org/" elementFormDefault="unqualified" targetNamespace="http://ws.med.healthcare.gs1br.org/" version="1.0">

  <xs:element name="sendMessage" type="tns:sendMessage"/>

  <xs:element name="sendMessageResponse" type="tns:sendMessageResponse"/>

  <xs:complexType name="sendMessage">
    <xs:sequence>
      <xs:element name="inboundMessage" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sendMessageResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="sendMessage">
    <wsdl:part element="tns:sendMessage" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sendMessageResponse">
    <wsdl:part element="tns:sendMessageResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Inbound">
    <wsdl:operation name="sendMessage">
      <wsdl:input message="tns:sendMessage" name="sendMessage">
    </wsdl:input>
      <wsdl:output message="tns:sendMessageResponse" name="sendMessageResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="InboundServiceSoapBinding" type="tns:Inbound">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sendMessage">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sendMessage">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sendMessageResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="InboundService">
    <wsdl:port binding="tns:InboundServiceSoapBinding" name="InboundPort">
      <soap:address location="http://localhost:8080/hc-gs1-br-WA/Inbound"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>