<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.med.healthcare.gs1br.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="OutboundService" targetNamespace="http://ws.med.healthcare.gs1br.org/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.med.healthcare.gs1br.org/" elementFormDefault="unqualified" targetNamespace="http://ws.med.healthcare.gs1br.org/" version="1.0">

  <xs:element name="getMessage" type="tns:getMessage"/>

  <xs:element name="getMessageResponse" type="tns:getMessageResponse"/>

  <xs:complexType name="getMessage">
    <xs:sequence>
      <xs:element name="queryRequest" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getMessageResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getMessage">
    <wsdl:part element="tns:getMessage" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getMessageResponse">
    <wsdl:part element="tns:getMessageResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Outbound">
    <wsdl:operation name="getMessage">
      <wsdl:input message="tns:getMessage" name="getMessage">
    </wsdl:input>
      <wsdl:output message="tns:getMessageResponse" name="getMessageResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OutboundServiceSoapBinding" type="tns:Outbound">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getMessage">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getMessage">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getMessageResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OutboundService">
    <wsdl:port binding="tns:OutboundServiceSoapBinding" name="OutboundPort">
      <soap:address location="http://localhost:8080/hc-gs1-br-WA/Outbound"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>